Update eclass patches

diff --git a/engine/docker/bob-portage/patches/0003-Revert-acct-user.eclass-Fixing-user-group-creation-w.patch b/engine/docker/bob-portage/patches/0003-Revert-acct-user.eclass-Fixing-user-group-creation-w.patch
--- a/engine/docker/bob-portage/patches/0003-Revert-acct-user.eclass-Fixing-user-group-creation-w.patch
+++ b/engine/docker/bob-portage/patches/0003-Revert-acct-user.eclass-Fixing-user-group-creation-w.patch
@@ -1,6 +1,16 @@
-diff -rupN gentoo/eclass/acct-user.eclass gentoo-patched/eclass/acct-user.eclass
---- gentoo/eclass/acct-user.eclass	2023-01-06 13:04:25.871008804 +0100
-+++ gentoo-patched/eclass/acct-user.eclass	2023-01-06 13:10:36.408013419 +0100
+From c1d6ba1310f777ff823b4c43c68f1929f9e7a199 Mon Sep 17 00:00:00 2001
+From: Erik Dannenberg <erik.dannenberg@xtrade-gmbh.de>
+Date: Tue, 27 Jun 2023 20:33:30 +0200
+Subject: [PATCH] Revert-acct-user.eclass-Fixing-user-group-creation-w
+
+---
+ eclass/acct-user.eclass | 31 +++----------------------------
+ 1 file changed, 3 insertions(+), 28 deletions(-)
+
+diff --git a/eclass/acct-user.eclass b/eclass/acct-user.eclass
+index f658aa0eabc3..0b1d1a37d794 100644
+--- a/eclass/acct-user.eclass
++++ b/eclass/acct-user.eclass
 @@ -198,15 +198,8 @@ eislocked() {
  	*)
  		# NB: 'no password' and 'locked' are indistinguishable
@@ -19,7 +29,7 @@ diff -rupN gentoo/eclass/acct-user.eclass gentoo-patched/eclass/acct-user.eclass
  		;;
  	esac
  }
-@@ -359,10 +352,6 @@ acct-user_pkg_preinst() {
+@@ -357,10 +350,6 @@ acct-user_pkg_preinst() {
  			opts+=( --uid "${_ACCT_USER_ID}" )
  		fi
  
@@ -28,9 +38,9 @@ diff -rupN gentoo/eclass/acct-user.eclass gentoo-patched/eclass/acct-user.eclass
 -		fi
 -
  		elog "Adding user ${ACCT_USER_NAME}"
- 		useradd "${opts[@]}" "${ACCT_USER_NAME}" || die
+ 		useradd "${opts[@]}" "${ACCT_USER_NAME}" || die "useradd failed with status $?"
  		_ACCT_USER_ADDED=1
-@@ -371,13 +360,7 @@ acct-user_pkg_preinst() {
+@@ -369,13 +358,7 @@ acct-user_pkg_preinst() {
  	if [[ ${_ACCT_USER_HOME} != /dev/null ]]; then
  		# default ownership to user:group
  		if [[ -z ${_ACCT_USER_HOME_OWNER} ]]; then
@@ -45,7 +55,7 @@ diff -rupN gentoo/eclass/acct-user.eclass gentoo-patched/eclass/acct-user.eclass
  		fi
  		# Path might be missing due to INSTALL_MASK, etc.
  		# https://bugs.gentoo.org/691478
-@@ -429,10 +412,6 @@ acct-user_pkg_postinst() {
+@@ -427,10 +410,6 @@ acct-user_pkg_postinst() {
  		opts+=( --expiredate "" --unlock )
  	fi
  
@@ -54,9 +64,9 @@ diff -rupN gentoo/eclass/acct-user.eclass gentoo-patched/eclass/acct-user.eclass
 -	fi
 -
  	elog "Updating user ${ACCT_USER_NAME}"
- 	if ! usermod "${opts[@]}" "${ACCT_USER_NAME}" 2>"${T}/usermod-error.log"; then
- 		# usermod outputs a warning if unlocking the account would result in an
-@@ -481,10 +460,6 @@ acct-user_pkg_prerm() {
+ 	# usermod outputs a warning if unlocking the account would result in an
+ 	# empty password. Hide stderr in a text file and display it if usermod fails.
+@@ -497,10 +476,6 @@ acct-user_pkg_prerm() {
  		--shell /sbin/nologin
  	)
  
@@ -65,5 +75,8 @@ diff -rupN gentoo/eclass/acct-user.eclass gentoo-patched/eclass/acct-user.eclass
 -	fi
 -
  	elog "Locking user ${ACCT_USER_NAME}"
- 	usermod "${opts[@]}" "${ACCT_USER_NAME}" || die
+ 	usermod "${opts[@]}" "${ACCT_USER_NAME}" || die "usermod failed with status $?"
  }
+-- 
+2.39.3
+
